[package]
name = "counter"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
iced.version = "*"
iced.features = ["webgl", "fira-sans"]

# [target.'cfg(target_arch = "wasm32")'.dependencies]
# iced.features = ["webgl", "fira-sans"]

[dev-dependencies]
iced_test = "*"
